@startuml
title 基于GitHub的实验管理平台--类图
abstract class Users {
    <b>user_ID</b> （用户ID）
    username (真实姓名)
    password (登录密码)
    github_username (github用户名)
    prohibit (用户是否被禁用)
    permission (权限)
    contact_way (user联系方式)
}

class Teachers {
    <b>teacher_ID</b> （教师工号）
    department (老师所属部门)

}

class Students {
    <b>student_ID</b> （学号）
    grade (成绩)
    class (班级)

}

class Administrator {
    <b>admin_ID</b> （管理员账号）
}

class Course {
    <b>course_ID</b> （课程代码）
    course_name (课程名称)
    course_hour (总课时)
    if_selected (是否可选)

}

class Experiment {
  <b>experiment_ID</b>（实验ID）
     experiment_name(实验名称)
     experiment_aim(实验目的)
     experiment_surrounding(实验环境)
     experiment_content(实验内容)
     experiment_step(实验步骤)
     closing_date(提交截止日期)
     class_ID(所属班级号)

}

class Element {
    <b>element_ID</b> （打分项ID）
    exper_ID (实验ID)
    element_name (打分项名称)
    persent (分数百分比占比)

}
note top:老师负责学生的各项细节评分

class Score {
    <b>score_id</b>（成绩ID）
    <b>course_id</b>（上课ID）
    <b>test_id</b>（实验ID）
    score(分数)
    score_detail(详细分数项)
    comment(评语)
    update_date (评改日期)
}
note top:分数由各项 score_detail 相加
class Semesters{
    <b>semesters_ID</b>（学期序号）
    semesters_name(学期名称)
    start_date(开始时间)
    end_date(结束时间)
    if_current(是否当前学期)
    if_elective(当前能否选课)
}
class Classes{
    <b>class_ID</b>（班级号）
    teacher_ID(选课老师工号)
    course_ID(老师选取课程的ID)
    semester_ID(学期序号)
}
class Student_course{
    <b>course_ID</b>（课程ID）
    student_ID(学号)
    class_ID(班级号)
}

Users <|-- Students
Users <|-- Teachers
Users <|-- Administrator

Classes "0..1 "<--"1..*" Teachers
Classes " 1 "<-right--"1..*" Course
Classes " * "--> " 1 " Semesters
Classes " 1 "<-down-" 1..* " Student_course

Teachers "1" -- "*" Course:选课
Students"1" -- "*" Course:选课
Course "1" -- "*" Experiment

Experiment "1" -- "*" Element:实验打分项
Experiment "1" -- "1" Score: 实验成绩

@enduml