@startuml
title 基于GitHub的实验管理平台--用例图

actor Administrator
actor Users
actor Teachers
actor Students

Users <|-- Students
Users <|-- Teachers
Users <|-- Administrator

package   用户用例集 {
    Users -up-> (登录)
    Users -up-> (修改密码)
    Users -up-> (查看用户信息)
    Users -up-> (修改用户信息)
    Users -up-> (查看课程信息)
    Users -up-> (登出)
}

package   业务用例集 {
    Administrator --> (管理课程信息)
    Administrator --> (学期管理)
    Administrator--> (管理Users账户信息)

    Teachers --> (评分细则管理)
    Teachers --> (成绩发布管理)
    Teachers --> (课程实验管理)

    Students --> (选择课程)
    Students --> (查看成绩)
    Students --> (查看已选课程)
    Students --> (退选已选课程)


}

@enduml